test('Our first test', () => {
  throw new Error('Something went wrong.');
});